name: doubles_recombined_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.1.6
  google_mobile_ads: ^1.2.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

